[ 2025-07-08 16:54:33,512 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2025-07-08 16:54:33,512 ] root - INFO - Getting the data from mongodb
[ 2025-07-08 16:54:33,512 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2025-07-08 16:54:33,513 ] root - INFO - Exporting data from mongodb
[ 2025-07-08 16:54:34,132 ] root - ERROR - Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\configuration\mongo_db_connection.py] at line number [54]: The DNS query name does not exist: _mongodb._tcp.cluster0.yfqovoi.mongodb.net.
[ 2025-07-08 16:54:34,132 ] root - ERROR - Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\data_access\proj_data.py] at line number [20]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\configuration\mongo_db_connection.py] at line number [54]: The DNS query name does not exist: _mongodb._tcp.cluster0.yfqovoi.mongodb.net.
[ 2025-07-08 16:54:34,132 ] root - ERROR - Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\data_access\proj_data.py] at line number [20]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\configuration\mongo_db_connection.py] at line number [54]: The DNS query name does not exist: _mongodb._tcp.cluster0.yfqovoi.mongodb.net.
[ 2025-07-08 16:54:34,132 ] root - ERROR - Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\data_access\proj_data.py] at line number [20]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\configuration\mongo_db_connection.py] at line number [54]: The DNS query name does not exist: _mongodb._tcp.cluster0.yfqovoi.mongodb.net.
[ 2025-07-08 16:54:34,133 ] root - ERROR - Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\pipline\training_pipeline.py] at line number [47]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\data_access\proj_data.py] at line number [20]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\configuration\mongo_db_connection.py] at line number [54]: The DNS query name does not exist: _mongodb._tcp.cluster0.yfqovoi.mongodb.net.
[ 2025-07-08 16:54:34,133 ] root - ERROR - Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\pipline\training_pipeline.py] at line number [59]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\pipline\training_pipeline.py] at line number [47]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\data_access\proj_data.py] at line number [20]: Error occurred in python script: [C:\Users\joshi\OneDrive\Desktop\Vehicle-Insurance-MLOps-pipeline\src\configuration\mongo_db_connection.py] at line number [54]: The DNS query name does not exist: _mongodb._tcp.cluster0.yfqovoi.mongodb.net.
